BRB-38 H5P-renderer
schul-cloud/nuxt-client pull request #2437
Opened 2023-03-13 11:35 UTC by ddeiters

# Short Description

In order to display the H5P content for thuringia, we have to use the rendering service of Edu-Sharing. The renderer with content is displayed in an Iframe. Therefor, we fetch the rendering service from Edu-Sharing and load it into the Iframe.
**Do not merge before BC-2945-es-kubernetes is merged into main!**

## Links to Ticket and related Pull-Requests

Epic with related tickets: https://ticketsystem.dbildungscloud.de/browse/BRB-38
Initiative: https://docs.dbildungscloud.de/pages/viewpage.action?pageId=190776231#expand-Abgrenzung
Documentation: https://docs.dbildungscloud.de/display/DBH/H5P
PR schulcloud-server: https://github.com/hpi-schul-cloud/schulcloud-server/pull/3985
PR dof_app_deploy: https://github.com/hpi-schul-cloud/dof_app_deploy/pull/484

## Changes

Therefor, we add a method for displaying the player of Edu-Sharing on the left side of the LernstoreDetailView.vue in an Iframe. Additionally, we change the info-text on the right side of the LernstoreDetailView.vue to explain the usage of the player on the left side. And we hide the button 'Zum Lerninhalt', because it is not needed for H5P elements.

## Data-security
Nothing related to data-security.

## Deployment
Nothing related to deployment.

## New Repos, NPM packages or vendor scripts
No changes, nothing added.

## Screenshots of UI changes
[LernstoreDetailView](https://docs.dbildungscloud.de/display/DBH/H5P?preview=/200147180/253231237/h5p_LernstoreDetailView.png)
[LernstoreCollection](https://docs.dbildungscloud.de/display/DBH/H5P?preview=/200147180/253231236/h5p_collection_overview.png)

## Checklist before merging

- [X] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [X] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [X] UX/UI: All changes were made in close consultation with the UI team

2023-03-21 07:45 UTC, MartinSchuhmacher requested changes

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/components/molecules/LernStorePlayer.unit.js
> +	it("Renders spinner", () => {
maybe checking for the conditions the spinner is shown at makes more sense here

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/components/molecules/LernStorePlayer.vue
> +export default {
new components should be written with `defineComponent` like for example in `CardElementWrapper.vue`

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/components/organisms/AddContentButton.vue
> +			if (getMediatype(this.resource) == "file-h5p") {
why no explicit checking with `===` ?

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/components/organisms/AddContentButton.vue
> +				const baseUrlH5p = this.$axios.defaults.baseURL.slice(0, -4);
where does the `-4` come from? can that be a variable for clarification?

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/components/organisms/AddContentButton.vue
> +					if (getMediatype(element) == "file-h5p") {
same as above

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/components/organisms/LernstoreDetailView.vue
> +		<div ref="icons" class="icons" :style="{ 'justify-content': 'flex-end' }">
use classes for styling, no inline

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/components/organisms/LernstoreDetailView.vue
> +					v-else-if="shouldShowPlayer && window.width < 768"
could that be solved with a `@media` query in styles instead of in the template?

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/pages/LernStoreOverview.page.vue
> +				//contentModule.clearResources();
remove comments if not needed anymore

2023-03-21 07:45 UTC, MartinSchuhmacher commented on src/pages/LernStoreOverview.page.vue
> +				//contentModule.clearResources();
^

2023-03-21 08:30 UTC, Loki-Afro submitted a review, later dismissed

2023-03-21 08:30 UTC, Loki-Afro commented on dockerconf/nginx.conf.template
> -    set $csp "default-src 'self'; base-uri 'self'; script-src 'nonce-$request_id' 'strict-dynamic' 'unsafe-inline' https:; object-src 'none'; font-src 'self' data:; img-src 'self' data:; style-src 's
use env vars to only set the needed ones.

2023-03-24 10:42 UTC, arnegns requested changes

2023-03-24 10:42 UTC, arnegns commented on src/components/molecules/LernStorePlayer.vue
> +export default {
Here you should use the vue 3 composition api https://vuejs.org/api/composition-api-setup.html

2023-03-24 10:42 UTC, arnegns commented on src/components/molecules/LernStorePlayer.vue
> +			await this.$axios
You are calling the server api? for v3 you can use the api open generated api and repsponses.
For v1 i would create an composable https://vuejs.org/guide/reusability/composables.html#what-is-a-composable.
Then you can call it here. Please use an interface for the response and map it here to a type / interface / class

2023-03-24 10:42 UTC, arnegns commented on src/components/molecules/LernStorePlayer.vue
> +		async getPlayer() {
Please use typescript and add types

2023-03-24 10:42 UTC, arnegns commented on src/components/molecules/LernStorePlayer.vue
> +<style>
in general i would add scoped to every style in a component https://vue-loader.vuejs.org/guide/scoped-css.html. Especially if you use style classes with a generic name like spinner

2023-03-24 10:42 UTC, arnegns commented on src/components/molecules/LernStorePlayer.vue
> +export default {
You can see the usage like here https://github.com/hpi-schul-cloud/nuxt-client/blob/4343208726757fe1d252202b6985efc731380d1c/src/components/administration/external-tool/ExternalToolConfigParameter.vue#L41-L41

2023-03-24 10:42 UTC, arnegns commented on src/components/molecules/LernStorePlayer.vue
> +<template>
I think the page molecules is wrong / deprecated. I would move it components in a new folder

2023-03-24 10:42 UTC, arnegns commented on src/utils/helpers.js
> +export const isVideoContent = (resource) => {
I would prefer to move the new functions to a composable, typescript and types. It seems to be h5p specific

2023-03-24 10:46 UTC, arnegns commented on src/pages/LernStoreOverview.page.vue
>  			this.$options.debounce = setInterval(() => {
Please use the composition api and the onBeforeUnmount hook to to this. Something like that:

`import { onMounted, onBeforeUnmount } from 'vue';

export default {
  setup() {
    const intervalId = setInterval(() => {
      contentModule.clearResources();
    }, 

    onBeforeUnmount(() => {
      clearInterval(intervalId);
    });
  },
};`

2023-03-24 14:51 UTC, ddeiters commented on src/components/organisms/AddContentButton.vue
> +			if (getMediatype(this.resource) == "file-h5p") {
Done in last commit.

2023-03-24 15:03 UTC, ddeiters commented on src/components/organisms/LernstoreDetailView.vue
> +		<div ref="icons" class="icons" :style="{ 'justify-content': 'flex-end' }">
Done in last commit.

2023-03-24 15:03 UTC, ddeiters commented on src/pages/LernStoreOverview.page.vue
> +				//contentModule.clearResources();
Done in last commit.

2023-03-24 15:04 UTC, ddeiters commented on src/pages/LernStoreOverview.page.vue
> +				//contentModule.clearResources();
Done in last commit.

2023-03-24 15:06 UTC, ddeiters commented on src/components/organisms/AddContentButton.vue
> +				const baseUrlH5p = this.$axios.defaults.baseURL.slice(0, -4);
The slice-method cuts the last four characters of from the string. In this case, it is the '/api' at the end of the global variable. We only need this URL in this context, so that in my opinion a new global variable is out of scope.

2023-03-28 07:00 UTC, ddeiters commented on src/components/organisms/LernstoreDetailView.vue
> +					v-else-if="shouldShowPlayer && window.width < 768"
Done in last commit.

2023-03-28 12:27 UTC, ddeiters commented on src/components/molecules/LernStorePlayer.vue
> +export default {
Done in last commit.

2023-03-28 13:59 UTC, ddeiters commented on src/components/molecules/LernStorePlayer.unit.js
> +	it("Renders spinner", () => {
New tests done in last commit.

2023-03-28 14:05 UTC, ddeiters commented on src/components/molecules/LernStorePlayer.vue
> +		async getPlayer() {
Done.

2023-03-29 09:18 UTC, ddeiters commented on dockerconf/nginx.conf.template
> -    set $csp "default-src 'self'; base-uri 'self'; script-src 'nonce-$request_id' 'strict-dynamic' 'unsafe-inline' https:; object-src 'none'; font-src 'self' data:; img-src 'self' data:; style-src 's
@Loki-Afro I add an env variable and put the URL's to dof_app_deploy. Works fine on dev-systems. Furthermore, I delete the unnecessary 'data:'.

2023-03-29 11:53 UTC, ddeiters commented on src/components/molecules/LernStorePlayer.vue
> +<style>
Done in last commit.

2023-03-30 06:25 UTC, ddeiters commented on src/components/molecules/LernStorePlayer.vue
> +<template>
Done

2023-03-30 09:18 UTC, arnegns approved these changes

2023-03-30 11:50 UTC, MartinSchuhmacher commented on src/components/organisms/AddContentButton.vue
> +				const baseUrlH5p = this.$axios.defaults.baseURL.slice(0, -4);
agree, I was just thinking of a solution to see, what exactly is cut of there and if there could be another case where accidentally something else is taken as baseURL and then cut off. So at least checking for the "api" in the url maybe before cutting? or is that usecase totally away from reality? ^^

2023-04-03 06:21 UTC, MartinSchuhmacher submitted a review, later dismissed

2023-04-03 09:54 UTC, MartinSchuhmacher submitted a review, later dismissed

2023-04-04 12:56 UTC, MartinSchuhmacher submitted a review, later dismissed

2023-04-04 13:39 UTC, odalys-dataport requested changes

2023-04-04 13:39 UTC, odalys-dataport commented on src/components/lern-store/LernStorePlayer.vue
> +	methods: {
please move this into the setup method as well. you can use the onMounted hook an declare the method inside the setup function

2023-04-04 14:36 UTC, marode-cap commented on src/components/lern-store/LernStorePlayer.vue
> +	methods: {
Changed in last commit

2023-04-05 19:13 UTC, odalys-dataport submitted a review, later dismissed

2023-04-06 07:40 UTC, CeEv commented on src/pages/LernStoreDetails.page.vue
> +import LernstoreDetailView from "@/components/lern-store/LernstoreDetailView";
@odalys-dataport is this new guidline to remove organisms strcuture and switch it to context?

2023-04-06 07:43 UTC, CeEv commented on src/utils/helpers.js
> +	return;
If return nothing the best way to handle it?

2023-04-06 07:44 UTC, odalys-dataport commented on src/pages/LernStoreDetails.page.vue
> +import LernstoreDetailView from "@/components/lern-store/LernstoreDetailView";
Yes, we want to get rid of the atomic design structure and instead sort by feature

2023-04-06 07:45 UTC, CeEv commented on src/pages/LernStoreDetails.page.vue
> +import LernstoreDetailView from "@/components/lern-store/LernstoreDetailView";
ok thank you

2023-04-06 08:56 UTC, SteKrause commented on src/utils/helpers.js
> +	return;
@CeEv Changed handling of getID.

2023-04-06 08:58 UTC, CeEv approved these changes

2023-04-11 09:38 UTC, merged