BC-6676 - Use v3 config
schul-cloud/nuxt-client pull request #3145
Opened 2024-03-13 12:16 UTC by bischofmax

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [x] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-03-19 10:50 UTC, uidp commented on src/main.ts
> +	await envConfigModule.loadConfiguration({ optional: isDevelopment });
As I understand `optional === true` also means that the frontend will start without complaining when the core config is not available (not only the file config). Is that intended? Or should we differentiate which one actually has failed?

2024-03-19 10:50 UTC, uidp commented on src/pages/administration/teacher-overview.unit.js
> +import mock$objects from "../../../tests/test-utils/pageStubs";
Maybe while we're at it: should be changed to `@@/tests/test-utils/pageStubs`

2024-03-19 10:50 UTC, uidp commented on src/store/env-config.ts
> +	get getAdminToggleStudentLernstoreViewEnabled(): boolean {
Why was `public` only added to some of the getters/methods? I think when they're `public` by default we don't really have to write them but at least the code should be consistent.

2024-03-19 10:50 UTC, uidp commented on src/store/env-config.ts
> +				await Promise.allSettled(configCalls);
(See above comment regarding `optional === true`.)

2024-03-20 10:29 UTC, SevenWaysDP commented on src/components/organisms/administration/GeneralSettings.unit.js
> +			I18N__AVAILABLE_LANGUAGES: [Language.De, Language.En, Language.Es],
```suggestion
			I18N__AVAILABLE_LANGUAGES: [Language.De, Language.En, Language.Es].join(','),
```
???

2024-03-20 10:29 UTC, SevenWaysDP commented on src/components/organisms/administration/GeneralSettings.vue
> +			return this.availableLanguages.map((lang) => {
Zur obere Frage ob das einzige stelle ist wo wir als string bräuchten?

2024-03-20 12:04 UTC, CeEv commented on src/store/env-config.ts
> -			Object.entries(requiredVars).forEach(([key]) => {
Bewusst nicht. Wenn es wieder rein kommt wäre es nur schön das in einer extra Methode zu haben und evtl. nur für den Development Modus.

2024-03-20 12:43 UTC, CeEv commented on src/components/lern-store/LernstoreDetailView.vue
> +			return process.env.SC_THEME === SchulcloudTheme.Brb;
Funktioniert die Methode überhaupt noch mit den Ausbau von Nuxt?

2024-03-20 12:44 UTC, CeEv commented on src/components/molecules/AdminTableLegend.vue
>  			switch (process.env.SC_THEME) {
Guter Umbau, aber gleiche Fragen ...funktioniert das überhaupt? Woher kommt process.env im Browser des clients?

2024-03-20 12:49 UTC, SevenWaysDP commented on src/store/env-config.ts
> +	env: ConfigResponse = {
Kann das auch in extra Datei verschoben werden um dann im tests/test-utils/factory/envsFactory.ts zu verwenden, macht das Sinn?

2024-03-20 12:51 UTC, CeEv commented on src/main.ts
> +	await envConfigModule.loadConfiguration({ optional: isDevelopment });
Is already resolved, but as hind it is possible with combination of Promise.all and Promise.settled if we like. But maybe not nessasary if you want to start the client without server it always fail.

2024-03-20 13:02 UTC, CeEv requested changes

2024-03-20 13:02 UTC, CeEv commented on tests/test-utils/factory/envsFactory.ts
> +export const envsFactory = Factory.define<ConfigResponse>(() => ({
Es gibt einige Stellen wo man die factory hätte verwenden können.

2024-03-25 07:10 UTC, CeEv submitted a review, later dismissed

2024-03-25 12:09 UTC, CeEv approved these changes
Bitte noch die 3 sonar Hinweise anschauen.

2024-03-26 07:46 UTC, CeEv approved these changes

2024-03-26 09:28 UTC, merged