BC-7282 - Adjust Sidebar Toggle Button Placement
schul-cloud/nuxt-client pull request #3267
Opened 2024-05-31 07:50 UTC by MartinSchuhmacher

# Short Description

For a smoother transition of the sidebar we want to adjust the cloud logo and toggle button placement.

## Links to Ticket and related Pull-Requests
BC-7282
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3453

## Changes
- adjusting logo and expand menu dependend on sidebar status
- move colors to base options file
- fix opacity on user menu

## Screenshots of UI changes
OPEN sidebar
![grafik](https://github.com/hpi-schul-cloud/nuxt-client/assets/55735359/f130ee3e-5bc5-4904-866c-165199951f0c)

CLOSED sidebar
![grafik](https://github.com/hpi-schul-cloud/nuxt-client/assets/55735359/13a5cf0b-875c-487d-83e7-7c862e0f5b4d)

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [x] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-06-11 08:02 UTC, odalys-dataport requested changes

2024-06-11 08:02 UTC, odalys-dataport commented on src/modules/ui/layout/topbar/TopbarLogo.vue
> +const altText = envConfigModule.getEnv.SC_TITLE + " " + t("global.topbar.logo");
Nice

2024-06-11 08:11 UTC, MartinSchuhmacher commented on src/modules/ui/layout/topbar/TopbarLogo.vue
> +<template>
you are right, will change that after waiting for maybe more feedback from Omar

2024-06-11 09:16 UTC, EzzatOmar approved these changes
I haven't found any issues.
Approved :)

2024-06-12 10:50 UTC, odalys-dataport requested changes

2024-06-12 10:50 UTC, odalys-dataport commented on src/locales/uk.ts
> +	"global.cloudlogo": "Логотип",
These should be written like "cloudLogo" :D

2024-06-12 10:50 UTC, odalys-dataport commented on src/modules/ui/layout/topbar/Topbar.vue
> +				v-if="!sidebarExpanded"
Please put the `v-if` at the beginning. This should be done by our formatter, no idea why it isn't doing that anywhere.

2024-06-13 10:43 UTC, odalys-dataport approved these changes

2024-06-13 12:40 UTC, merged